version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mesher
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # 외부 port는 5434로 지정하여 기존 Postgres와의 충돌 방지
    ports:
      - '5434:5432'

  app:
    build: .
    depends_on:
      - db
    ports:
      - '4000:4000'

volumes:
  postgres_data:
